services:
  backend:
    build:
      context: .
      dockerfile: llmapp04-main/llm-multiroute/Dockerfile
    container_name: llm_backend
    ports:
      - "8082:8082"
    volumes:
      - ./llmapp04-main/llm-multiroute/app:/app/app
    restart: always

